name = "simple-markdown-note-api"
main = "src/index.ts"
compatibility_date = "2026-03-29"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "simple-markdown-note-db"
database_id = "YOUR_DATABASE_ID_HERE"
migrations_dir = "../../packages/database/migrations"

[vars]
# Override Github actions CD
NODE_ENV = "development"
ALLOWED_ORIGIN="http://localhost:3000"
CLIENT_URL="http://localhost:3000"
EMAIL_FROM="onboarding@resend.dev"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
