name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Drizzle Schema
        run: |
          pnpm -F database run generate

      - name: Verify code style & Lint
        run: pnpm check

      - name: Type check
        run: pnpm typecheck

      - name: Setup test database
        run: pnpm -F database db:push
        env:
          DATABASE_URL: "file:./test.db"

      - name: Run tests
        run: pnpm test
